/* Material Files syscall source is split only to keep this vendored import reviewable. */
#include "syscall-part-01.inc"
#include "syscall-part-02.inc"
#include "syscall-part-03.inc"
#include "syscall-part-04.inc"
#include "syscall-part-05.inc"
#include "syscall-part-06.inc"
#include "syscall-part-07.inc"
#include "syscall-part-08.inc"
#include "syscall-part-09.inc"
#include "syscall-part-10.inc"
#include "syscall-part-11.inc"
#include "syscall-part-12.inc"
#include "syscall-part-13.inc"
#include "syscall-part-14.inc"
