[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [string] $ArchivePath,
    [Parameter(Mandatory)]
    [string] $Python,
    [Parameter(Mandatory)]
    [string] $AndroidCompiler,
    [switch] $Replace
)

$ErrorActionPreference = 'Stop'
$expectedSha256 = '5370f98dc15f8c222ee1ce52cd61c8756a53be0dc57cc4c1b0714d5a09ad74fb'
$workspace = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$archive = (Resolve-Path $ArchivePath).Path
$compiler = (Resolve-Path $AndroidCompiler).Path
$destination = Join-Path $workspace 'app/src/main/native/vc_core/botan/arm64-v8a'
$digest = (Get-FileHash -LiteralPath $archive -Algorithm SHA256).Hash.ToLowerInvariant()
if ($digest -ne $expectedSha256) {
    throw "Botan archive SHA-256 mismatch. Expected $expectedSha256, got $digest."
}

$staging = Join-Path ([System.IO.Path]::GetTempPath()) ("eds-botan-" + [guid]::NewGuid())
New-Item -ItemType Directory -Path $staging | Out-Null
try {
    # Windows bsdtar rejects a harmless .github path in the upstream xz
    # archive on some hosts. Use the caller-supplied Python runtime instead;
    # the archive was digest-verified before extraction.
    & $Python -c "import sys, tarfile; tarfile.open(sys.argv[1], 'r:xz').extractall(sys.argv[2])" $archive $staging
    if ($LASTEXITCODE -ne 0) { throw 'Could not unpack the Botan archive.' }
    $source = Get-ChildItem -LiteralPath $staging -Directory | Where-Object {
        Test-Path -LiteralPath (Join-Path $_.FullName 'configure.py')
    } | Select-Object -First 1
    if ($null -eq $source) { throw 'The Botan archive does not contain configure.py.' }

    $modules = @(
        'aes', 'aes_armv8', 'serpent', 'twofish', 'camellia', 'kuznyechik', 'cascade', 'xts', 'cpuid', 'cpuid_aarch64',
        'sha2_32', 'sha2_32_armv8', 'sha2_64', 'sha2_64_armv8', 'sha3', 'blake2', 'whirlpool', 'streebog',
        'pbkdf2', 'hmac', 'argon2', 'auto_rng', 'system_rng'
    ) -join ','
    Push-Location $source.FullName
    try {
        $buildDir = Join-Path $source.FullName 'eds-arm64-amalgamation'
        $installDir = Join-Path $buildDir 'install'
        & $Python configure.py --os=android --cpu=arm64 --cc=clang --cc-bin=$compiler --with-build-dir=$buildDir --prefix=$installDir --minimized-build --amalgamation "--enable-modules=$modules"
        if ($LASTEXITCODE -ne 0) { throw 'Botan configure.py failed.' }
    } finally {
        Pop-Location
    }

    $cpp = Get-ChildItem -LiteralPath $source.FullName -Recurse -Filter botan_all.cpp | Select-Object -First 1
    $header = Get-ChildItem -LiteralPath $source.FullName -Recurse -Filter botan_all.h | Select-Object -First 1
    if ($null -eq $cpp -or $null -eq $header) { throw 'Botan did not produce an amalgamation.' }
    $generated = (Get-Content -LiteralPath $cpp.FullName -Raw) + "`n" + (Get-Content -LiteralPath $header.FullName -Raw)
    foreach ($marker in @('BOTAN_HAS_CPUID', 'BOTAN_HAS_AES_ARMV8', 'BOTAN_HAS_SHA2_32_ARMV8', 'BOTAN_HAS_SHA2_64_ARMV8')) {
        if ($generated -notmatch "(?m)^#define\s+$marker\b") {
            throw "Generated Botan amalgamation lacks required arm64 implementation marker $marker."
        }
    }

    if ((Test-Path -LiteralPath $destination) -and -not $Replace) {
        throw "Refusing to replace $destination without -Replace. Generated files remain staged at $staging."
    }
    if ($PSCmdlet.ShouldProcess($destination, 'replace Botan arm64 amalgamation')) {
        New-Item -ItemType Directory -Force -Path $destination | Out-Null
        Copy-Item -LiteralPath $cpp.FullName -Destination (Join-Path $destination 'vc_botan.cpp') -Force
        Copy-Item -LiteralPath $header.FullName -Destination (Join-Path $destination 'vc_botan.h') -Force
        $generatedCpp = Get-Content -LiteralPath (Join-Path $destination 'vc_botan.cpp') -Raw
        # configure.py embeds its temporary absolute build directory in a
        # comment. Normalize that non-semantic line so identical inputs yield
        # byte-stable amalgamation output across machines and runs.
        $generatedCpp = [regex]::Replace($generatedCpp, "(?m)^\s*\* 'configure\.py .*\r?\n", " * generated by tools/generate-botan-arm64.ps1 from Botan 3.12.0`n")
        $generatedCpp.Replace('#include "botan_all.h"', '#include "vc_botan.h"') |
            Set-Content -LiteralPath (Join-Path $destination 'vc_botan.cpp') -NoNewline
        Write-Output "Regenerated Botan arm64 amalgamation from verified Botan 3.12.0 archive."
    }
} finally {
    if (Test-Path -LiteralPath $staging) { Remove-Item -LiteralPath $staging -Recurse -Force }
}
